baseURL = "https://peterampazzo.github.io/project-website-template/"
title = "Project Title"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Daniel Holmelund", "Christian Djurhuus", "Felix Burmester"]
    notebook = "/explainer-notebook.html"
    data = "https://www.clarin.si/repository/xmlui/handle/11356/1432"
    github = "https://github.com/DanielHolmelund/the-political-debate-in-britain-illuminated-through-quantitative-methods"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

